# Generated by Django 3.2.12 on 2022-02-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorlog_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='current_uses',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Tracks the number of times this token has been used', null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='max_uses',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='Tracks the maximum number of times this token can be used - defaults to VISITOR_TOKEN_USES.', null=True),
        ),
    ]
